---
title: "Data Import"
output: github_document
---

```{r}
  library(tidyverse)
  library(readxl)
  library(haven)
```

Import!

```{r}
litters_df= 
  read_csv("data/data_import_examples/data_import_examples/FAS_litters.csv")
```


Look at Data
```{r}
names(litters_df)
```


Update Names in 'litters_df'

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

```{r}
litters_df
```

Sometimes skiming data is neat?
```{r}
 skimr::skim(litters_df)
```

## Fix the missing
```{r}
litters_df = read_csv("data/data_import_examples/data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
```


##import pups data
```{r}
pups_df = read_csv("data/data_import_examples/data_import_examples/FAS_pups.csv", 
    skip = 3, 
    na = c("NA", ".", ""))
  pups_df = janitor::clean_names(pups_df)
```

```{r}
pups_df
```


##Okay what about Excel?

CSVs are great but sometimes you get an excel file.


```{r}
mlb_df = 
  read_excel("data/data_import_examples/data_import_examples/mlb11.xlsx", )
```

Import LotR word counts

```{r}
fotr_df = 
  read_excel("data/data_import_examples/data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

## SAS??

Import the PULSE data
```{r}
pulse_df = read_sas("data/data_import_examples/data_import_examples/public_pulse_data.sas7bdat")

pulse_df= 
  janitor::clean_names(pulse_df)
```

## Why do I hate read.csv so much??

```{r, eval =FALSE}
litters_df_base = 
  read.csv("data/data_import_examples/data_import_examples/FAS_litters.csv")
```


